### ISSUE TITLE
Implement Exphash / Frankomoto

### ISSUE THREAD

**Issue by chrisfranko** [chfast/ethash#126]
In gexp we made these changes

https://github.com/expanse-org/go-expanse/commit/5433a50a09db510e55e8350ac539ad6323f62251

The idea is after a predetermined epoch switch from hashimoto to frankomoto.

Frankomoto and Hashimoto are similar except that instead of Keccak512 and Keccak256 it uses Sha512 and Sha512_256.

**Comment by chrisfranko** [comment]
seedhash Generator - https://github.com/expanse-org/go-expanse/blob/5433a50a09db510e55e8350ac539ad6323f62251/consensus/ethash/algorithm.go#L130

generateCache - https://github.com/expanse-org/go-expanse/blob/5433a50a09db510e55e8350ac539ad6323f62251/consensus/ethash/algorithm.go#L190

generateDataset - https://github.com/expanse-org/go-expanse/blob/5433a50a09db510e55e8350ac539ad6323f62251/consensus/ethash/algorithm.go#L316

frankomoto - https://github.com/expanse-org/go-expanse/blob/5433a50a09db510e55e8350ac539ad6323f62251/consensus/ethash/algorithm.go#L391

**Comment by chfast** [comment]
Sorry, but we are not going to maintain random modifications to Ethash.

**Comment by chrisfranko** [comment]
Mostly I was trying to start communication with you because I was seeking your help. You helped ubq with their change in 2018 and I was hoping you could help us with ours, but after a year of waiting for some sort of reply I gave up on that dream. :) I sent you messages on discord and everything. At the time we had a $20k budget for it, but not so much now. :/
