### ISSUE TITLE
can't compile on 32 bits

### ISSUE THREAD

**Issue by etam** [chfast/ethash#145]
openSUSE Tumbleweed, gcc 9.2.1
```
[ 39%] Building C object test/integration/compilation/CMakeFiles/test-compile-c90.dir/__/__/__/lib/ethash/keccak.c.o
cd /home/abuild/rpmbuild/BUILD/ethash-0.4.4/build/test/integration/compilation && /usr/bin/cc  -I/home/abuild/rpmbuild/BUILD/ethash-0.4.4/include  -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=6 -g -DNDEBUG -O2 -g -DNDEBUG   -pedantic -Werror -Wall -Wextra -Wconversion -Wsign-conversion -Wno-unknown-pragmas -fno-stack-protector -Wimplicit-fallthrough -mtune=generic -std=c90 -o CMakeFiles/test-compile-c90.dir/__/__/__/lib/ethash/keccak.c.o   -c /home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c
/home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c: In function 'keccak':
/home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c:89:5: error: integer constant is too large for 'long' type [-Werror=long-long]
   89 |     state[(block_size / word_size) - 1] ^= 0x8000000000000000;
      |     ^~~~~
cc1: all warnings being treated as errors
```

**Comment by Saikatsaha1996** [comment]
Is this miner?

> openSUSE Tumbleweed, gcc 9.2.1
> 
> ```
> [ 39%] Building C object test/integration/compilation/CMakeFiles/test-compile-c90.dir/__/__/__/lib/ethash/keccak.c.o
> cd /home/abuild/rpmbuild/BUILD/ethash-0.4.4/build/test/integration/compilation && /usr/bin/cc  -I/home/abuild/rpmbuild/BUILD/ethash-0.4.4/include  -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=6 -g -DNDEBUG -O2 -g -DNDEBUG   -pedantic -Werror -Wall -Wextra -Wconversion -Wsign-conversion -Wno-unknown-pragmas -fno-stack-protector -Wimplicit-fallthrough -mtune=generic -std=c90 -o CMakeFiles/test-compile-c90.dir/__/__/__/lib/ethash/keccak.c.o   -c /home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c
> /home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c: In function 'keccak':
> /home/abuild/rpmbuild/BUILD/ethash-0.4.4/lib/ethash/keccak.c:89:5: error: integer constant is too large for 'long' type [-Werror=long-long]
>    89 |     state[(block_size / word_size) - 1] ^= 0x8000000000000000;
>       |     ^~~~~
> cc1: all warnings being treated as errors
> ```

**Comment by chfast** [comment]
I think this is fixed now.
