### ISSUE TITLE
how to use it in my project

### ISSUE THREAD

**Issue by chain789** [chfast/ethash#146]
When I link the libethash.a ，I get the following errors
/usr/bin/ld: //usr/local/lib/libethash.a(ethash.cpp.o): relocation R_X86_64_32 against `__gxx_personality_v0' can not be used when making a shared object; recompile with -fPIC
//usr/local/lib/libethash.a: error adding symbols: Bad value

**Comment by chfast** [comment]
Configure CMake with `-DCMAKE_POSITION_INDEPENDENT_CODE=TRUE`. The official binaries should be already built like so.
