### ISSUE TITLE
complete pow in python from eth_getwork or mining.notify to golden nonce

### ISSUE THREAD

**Issue by shahbaazlokh** [chfast/ethash#157]
Hi,
I am trying to understand ethash algo to make a cache and dag and pow to get the final golden nonce and hash.
I found some reference implementations in go language, but i am not familier with it.
is it possible to get a setp by step func or logic to get complete pow including dag generation logic and cache generation logic in python or c with actual blockheader or from block-explorer.

for mining here is so far i understand.
->pool will send a seed hash from which we need to determine block number.
-> from block number generate cache and dag
->pow(this i dont understand how it interacts with dag)

**Comment by chfast** [comment]
I can only offer:
- these test cases: https://github.com/chfast/ethash/blob/master/test/unittests/test_cases.hpp
- how these hashes are checked: https://github.com/chfast/ethash/blob/master/test/unittests/test_ethash.cpp#L529-L563
- and how to search a good nonce: https://github.com/chfast/ethash/blob/master/test/unittests/test_ethash.cpp#L667-L706.
