### ISSUE TITLE
cant compile on centos

### ISSUE THREAD

**Issue by etam89** [chfast/ethash#172]
CMake Error at CMakeLists.txt:229 (message):
  Failed to determine the source files for the regular expression backend

-- Configuring incomplete, errors occurred!
See also "/home/IC/.hunter/_Base/18e57a4/c197bbe/5c48e6d/Build/benchmark/Build/benchmark-Release-prefix/src/benchmark-Release-build/CMakeFiles/CMakeOutput.log".
See also "/home/IC/.hunter/_Base/18e57a4/c197bbe/5c48e6d/Build/benchmark/Build/benchmark-Release-prefix/src/benchmark-Release-build/CMakeFiles/CMakeError.log".
gmake[2]: *** [benchmark-Release-prefix/src/benchmark-Release-stamp/benchmark-Release-configure] Error 1
gmake[1]: *** [CMakeFiles/benchmark-Release.dir/all] Error 2
gmake: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/IC/.hunter/_Base/18e57a4/c197bbe/5c48e6d/Build/benchmark
[hunter ** FATAL ERROR **] [Directory:/home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/projects/benchmark]

------------------------------ ERROR -----------------------------
    https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html
------------------------------------------------------------------

CMake Error at /home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_error_page)
  /home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/modules/hunter_download.cmake:617 (hunter_fatal_error)
  /home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/projects/benchmark/hunter.cmake:32 (hunter_download)
  /home/IC/.hunter/_Base/Download/Hunter/0.23.224/18e57a4/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  test/benchmarks/CMakeLists.txt:5 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/IC/ethash/test/chfast/ethash/build/CMakeFiles/CMakeOutput.log".
See also "/home/IC/ethash/test/chfast/ethash/build/CMakeFiles/CMakeError.log".

**Comment by chfast** [comment]
Use `-DETHASH_BUILD_TESTS=OFF` CMake option.

**Comment by etam89** [comment]
thanks!. it works.

    On Wednesday, March 17, 2021, 05:38:52 AM PDT, Paweł Bylica ***@***.***> wrote:  
 
 


Use -DETHASH_BUILD_TESTS=OFF CMake option.
