### ISSUE TITLE
Verify against difficulty

### ISSUE THREAD

**Issue by chfast** [chfast/ethash#185]
The final hash verification is

    final_hash <= 2^256 / difficulty

The current verify() API takes `boundary = 2^256 / difficulty` instead of `difficulty`. The `boundary` is commonly used in mining for efficiency. However, for block hash verification this is not optimal because clients have to compute `2^256 / difficulty` inversion for every block hash.

We propose to add additional function which takes `difficulty` argument directly: `verify_against_difficulty()`.
Internally, we can perform much more efficient check:

    final_hash * difficulty <= 2^256

This has been tested and the formula is also valid for difficulty 0 and 1.

We also propose to rename `verify()`  to `verify_against_boundary()` to disambiguate.
And change `verify_final_hash()` to `verify_final_hash_against_difficulty()` as this function is suppose to be used for quick block hash verification.

**Comment by AndreaLanfranchi** [comment]
I'm totally in favor of this.
