### ISSUE TITLE
setup.py issue

### ISSUE THREAD

**Issue by kralverde** [chfast/ethash#214]
When trying to install on python, I get this error:

```
Creating library build\temp.win32-3.9\Release\build\temp.win32-3.9\Release\_ethash.lib and object build\temp.win32-3.9\Release\build\temp.win32-3.9\Release\_ethash.exp
_ethash.obj : error LNK2001: unresolved external symbol _ethash_keccak512
_ethash.obj : error LNK2001: unresolved external symbol _ethash_hash
_ethash.obj : error LNK2001: unresolved external symbol _ethash_verify_against_boundary
_ethash.obj : error LNK2001: unresolved external symbol _ethash_keccak256
_ethash.obj : error LNK2001: unresolved external symbol _ethash_get_global_epoch_context
build\lib.win32-3.9\_ethash.pyd : fatal error LNK1120: 5 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120
```

Could anyone help me out?

**Comment by chfast** [comment]
Do you try to build from source or just install?

For install, it looks like wheel packages are not automatically published.

For build, I don't remember exactly how I did it but can check the CI script:
- https://github.com/chfast/ethash/blob/master/scripts/ci/python_build_wheels.sh
- https://github.com/chfast/ethash/blob/master/appveyor.yml

**Comment by kralverde** [comment]
After many sleepless nights, I built it using visual studios 2017 build tools instead of the 2022 vs. That worked for me. No idea what caused it though.
