### ISSUE TITLE
Upload 0.9.0-alpha.0 to PyPi

### ISSUE THREAD

**Issue by andrei-kondakov** [chfast/ethash#217]
@chfast Hello!

I want to upload a new package version (0.9.0-alpha.0) on PyPi.
I made a fork of the repository with following changes: https://github.com/andrei-kondakov/ethash/commit/633cdc776c73afd63355c23b6af8d532b55a06a6.

I renamed the package name to ethash2 in my fork and add myself as maintainer of this package. I did not change the author parameter, you are still listed there. Is it okay?

I want to use this package on ubuntu 20.04 later.
I'm creating a wheel on a Mac (m1) and got following error during upload to pypi:
```
(venv) andrei@m1 ethash % pip install twine              
...
(venv) andrei@m1 ethash % python setup.py bdist_wheel    
....
(venv) andrei@m1 ethash % twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
InvalidDistribution: Unknown distribution format: 'include'
```

Can u tell me how you published the package on PyPI? 

Thank you!

**Comment by chfast** [comment]
I don't remember honestly. I believe I was uploading them manually somehow. The wheel build instructions are in https://github.com/chfast/ethash/blob/master/circle.yml#L230.

Maybe I can automate this in CI too. Do you use this package?

**Comment by andrei-kondakov** [comment]
Yes, I do. I want to test your implementation instead of https://pypi.org/project/pyethash/ for ETH.

**Comment by chfast** [comment]
I have uploaded wheels for the 0.9.0 release. https://pypi.org/project/ethash/0.9.0/#files

**Comment by andrei-kondakov** [comment]
@chfast Thank you! Can you explain process of upload? I want to upload to PyPi my implementation of the etchash algo (fork of your repo).

**Comment by chfast** [comment]
The CI builds all wheels and the source package (available in artifacts). I manually download them and upload with twine. This can also be automated but I didn't for security reasons.

**Comment by andrei-kondakov** [comment]
Hello!

I got ModuleNotFoundError on my ubuntu 18.04.6, python 3.8.11 (and 3.9) after installing of ethash==0.9.0:

```
(venv) root@ubuntu # pip install ethash
Collecting ethos
  Using cached ethash-0.9.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (36 kB)
Requirement already satisfied: cffi>=1.12 in /home/user/venv/lib/python3.8/site-packages (from ethash) (1.15.0)
Requirement already satisfied: pycparser in /home/user/venv/lib/python3.8/site-packages (from cffi>=1.12->ethash) (2.21)
Installing collected packages: ethash
Successfully installed ethash-0.9.0
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/home/user/venv/bin/python3.8 -m pip install --upgrade pip' command.
(venv) root@ubuntu  # python
Python 3.8.11 (default, Sep  8 2021, 15:31:46) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ethash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ethash'
```

@chfast Can you help?
Thank you
