### ISSUE TITLE
How to add ECIP-1099 here?

### ISSUE THREAD

**Issue by andrei-kondakov** [chfast/ethash#218]
I want to make a Python package for verifying an ETC mining shares.

Tried to integrate ECIP-1099: https://ecips.ethereumclassic.org/ECIPs/ecip-1099
I looked at the repository which already tried to do this: https://github.com/etclabscore/cpp-etchash
My same attemp here: https://github.com/andrei-kondakov/ethash/commit/2699d03f560c5871d23933cb8780036ffb4408ff

Etclabscore and my solution don't work on this case of real mining ETC share:

- height - 14790284 
- nonce - 0x4f29c0e5dc784d8b
- mining_hash - 0x32d6c83f7fc493aa224a8fcc3ac007e6113d28ed70717e7d5a7505d72d4bdd7f
- mix_hash - 0xb27518ae34f7e81c56a4dedb81df93c4d4301d90643678044b3445ded0b331ce
- final_hash - 000000016454ac15829b7d6158f4be151ba9a9aa42e905153c7c43f211decb9f

```
import unittest

import ethash


class TestEthash(unittest.TestCase):
    epoch_number = 493 # (we used old epoch here: 493 like in ETH?, real is 246)
    nonce = 0x4f29c0e5dc784d8b
    header_hash = bytes.fromhex(
        '32d6c83f7fc493aa224a8fcc3ac007e6113d28ed70717e7d5a7505d72d4bdd7f')
    mix_hash = bytes.fromhex(
        'b27518ae34f7e81c56a4dedb81df93c4d4301d90643678044b3445ded0b331ce')
    final_hash = bytes.fromhex(
        '000000016454ac15829b7d6158f4be151ba9a9aa42e905153c7c43f211decb9f')

    def test_hash(self):
        f, m = ethash.hash(self.epoch_number, self.header_hash, self.nonce)
        print(f.hex()) # <- 8a678cdfc607962405f0f543b9a3a046072079d197b4e364be04f2cd175ab31f
        print(m.hex()) # <- 3d93eb7ff453d852bf95e98e6c73ab92f64628a7c1e3f3b4110f80970a0af96d
        self.assertEqual(m, self.mix_hash) # fail
        self.assertEqual(f, self.final_hash) # fail
```

Whats wrong here? How to integrate ECIP-1099 correctly?
Thanks!

**Comment by andrei-kondakov** [comment]
@chfast @iquidus any help here?

**Comment by chfast** [comment]
I don't know what changes are required. But even if there were a PR ready I probably would not merged it because I didn't want to maintain it.
